### PR TITLE
Share options with subcommands

### LINKED ISSUE #244: setAllowAbbreviatedOptions fails on sub-command parameters
Demonstration code:

```java
class P1 {}
class P2 {
	@Parameter(names = "--hello")
	private int test;
}
P1 p1 = new P1();
P2 p2 = new P2();
JCommander j = new JCommander(p1);
j.addCommand("wonderful", p2);
j.setAllowAbbreviatedOptions(true);
j.parse(new String[]{"wond", "--he", "47"});
System.out.printf("command %s, test %d\n", j.getParsedCommand(), p2.test);
```

Raises:
```
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: --he
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:742)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:791)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at test.main.main(main.java:24)
```

### PR DESCRIPTION
**Pull request by simon04**
This fixes #244, #261. However, since `JCommander#getCommands` exposes subcommand `JCommander` objects, allowing to set custom settings on subcommands, this might break some very specific use-cases.

### CODE REVIEW

File: src/test/java/com/beust/jcommander/CmdTest.java [hunk 1]
```diff
@@ -88,4 +88,20 @@ public void testArgsWithDefaultCmd(String expected, boolean requireDefault,
...
+            @Parameter(names = "--hello")
+            private int test;
+        }
+        P1 p1 = new P1();
+        P2 p2 = new P2();
+        JCommander j = new JCommander(p1);
+        j.addCommand("wonderful", p2);
+        j.setAllowAbbreviatedOptions(true);
+        j.parse("wond", "--he", "47");
+        System.out.printf("command %s, test %d\n", j.getParsedCommand(), p2.test);
```
Comment (cbeust) [inline src/test/java/com/beust/jcommander/CmdTest.java]: Should probably be an `assert` here?

Comment (simon04) [inline src/test/java/com/beust/jcommander/CmdTest.java]: I added two `assertEquals` tests.

**Comment by cbeust** [comment]
Thanks!

**Comment by simon04** [comment]
@cbeust, due to this PR quite a few tickets are solved (see the initial comment).

**Comment by cbeust** [comment]
@simon-clarkstone I just closed these issues, thanks!
