### PR TITLE
Thread-safe and non-shared converter factories

### LINKED ISSUE #278: JCommander.addConverterFactory is not threadsafe
Make `JCommander.addConverterFactory()` a static method since it is only modifying a static variable. I'm hitting a `java.util.ConcurrentModificationException` because I did not realize this method wasn't threadsafe.

### PR DESCRIPTION
**Pull request by simon04**
Makes converter factories thread-safe and non-shared across commander instances.

Fixes #278

### CODE REVIEW

File: src/main/java/com/beust/jcommander/JCommander.java [hunk 1]
```diff
@@ -167,22 +167,18 @@ public int compare(ParameterDescription p0, ParameterDescription p1) {
     private int m_verbose = 0;
     private boolean m_caseSensitiveOptions = true;
     private boolean m_allowAbbreviatedOptions = false;
+    /**
+     * The factories used to look up string converters.
+     */
+    private final List<IStringConverterInstanceFactory> converterInstanceFactories = new CopyOnWriteArrayList<>();
```
Comment (cbeust) [inline src/main/java/com/beust/jcommander/JCommander.java]: Mind sticking to the `m_` convention?

Not crazy about it any more but let's be consistent.

Comment (simon04) [inline src/main/java/com/beust/jcommander/JCommander.java]: I don't care and pushed an altered version (`m_converterInstanceFactories`). :smile:

**Comment by cbeust** [comment]
Thanks!
