### PR TITLE
solve issue #501

### LINKED ISSUE #501: Cannot use @-syntax in conjunction with arguments starting with literal @
# Description

One cannot use the [`@`-syntax](https://jcommander.org/#_syntax) in conjunction with parameters that may contain a literal `@` at the beginning.

## Steps to reproduce:

In this repository: https://github.com/c-kunz/jcommander-conflicting-at-syntax

```bash
git clone https://github.com/c-kunz/jcommander-conflicting-at-syntax
cd jcommander-conflicting-at-syntax
mvn clean package
java -jar target/demo-jar-with-dependencies.jar -password @X
```

## Expected result

JCommander is able to parse the argument beginning with the literal `@` while also being able to parse additional arguments using the `@`-syntax.

## Actual result

JCommander interprets the argument starting with a literal `@` as a file containing additional arguments ([`@`-syntax](https://jcommander.org/#_syntax)):

`Exception in thread "main" com.beust.jcommander.ParameterException: Could not read file X: java.nio.file.NoSuchFileException: X`

## Workaround

One has to settle for the following workaround, basically disabling the `@`-syntax altogether:

```java
JCommander cli = ...
cli.setExpandAtSign(false);
```

## Proposal

Since this is an either-or situation, either disabling `@`-syntax or prohibiting arguments starting with a literal `@`, it would be nice to be able to **for example** specify parameters that lookup additional arguments in a file or specify parameters that ignore leading `@` signs.

### PR DESCRIPTION
**Pull request by HennyNile**
Fixes #501 
Hi! #501 mentioned can not use @-syntax in conjunction with arguments starting with literal @. I solve this proplem by changing the judge rule of @-syntax. The initail version recognizes the parameter value starting with @ as a file when ```expandAtSign``` is true whcih makes the program fail when some patameters' value just begin with @ and is not a file name. Then I add a judge rule that paramter value is not a file name when it begin with ```@/``` . This is because filename in most OS can not begin with ```/```, then the parameter value begin with ```@/``` must not be a filename. 
This change bring some benefits but also add some complexity. If you want a parameter value begins with ```@``` and not a file name  like ```@password```, you should transfer ```@/@password``` into.

### CODE REVIEW

**Comment by mkarg** [comment]
Thank you for looking into this. Indeed I do not like the idea of having a slash after `@`. Maybe we can find a solution that works without?

**Comment by mkarg** [comment]
@HennyNile Your PR is in conflict with the target branch. Can you please resolve the conflict and answer the open question? Thanks.

**Comment by mkarg** [comment]
@HennyNile Kindly requesting your response!

**Comment by mkarg** [comment]
No need to be sorry! :-)

**Comment by mkarg** [comment]
@HennyNile Any news? :-)

**Comment by HennyNile** [comment]
Hi, I am currently working on something important and will be available after July. If it's okay, I will address this issue at that time.

**Comment by HennyNile** [comment]
@mkarg  Hi, I’m currently working on this issue and will discuss it with you once I’ve found a suitable solution.

**Comment by mkarg** [comment]
> @mkarg Hi, I’m currently working on this issue and will discuss it with you once I’ve found a suitable solution.

Sounds great! :-)

**Comment by HennyNile** [comment]
@mkarg In retrospect of this problem, I found another way to solve it and don't change the initial usage of @ syntax.

While jcommander expands the @ syntax before it tries to parse the parameter values, it's hard to distinguish whether a string starting with @ is an @ syntax usage or a normal parameter value. Thus, I change to expand @ syntax during the parsing stage. If we meet a string starting with @ before we meet a parameter key, it is @ syntax usage. Otherwise, it is a normal parameter value.

Hope this solution helps.

File: src/main/java/com/beust/jcommander/JCommander.java [hunk 1]
```diff
@@ -735,6 +729,32 @@ private void parseValues(String[] args, boolean validate) {
...
+                List<String> fileArgs = readFile(fileName);
+                
+                // Create a new array to hold the expanded arguments
+                String[] newArgs = new String[args.length + fileArgs.size() - 1];
+
+                // Copy the existing arguments before the '@' argument
+                System.arraycopy(args, 0, newArgs, 0, i);
+
+                // Copy the arguments from the file
+                for (int j = 0; j < fileArgs.size(); j++) {
```
Comment (mkarg) [inline src/main/java/com/beust/jcommander/JCommander.java:747]: I don't think that performance plays a measurable role here, so we could simplify using `System.arraycopy(fileArgs.toArray(), 0, newArgs, i, fileArgs.length());` if you like. 😃

Comment (mkarg) [reply src/main/java/com/beust/jcommander/JCommander.java:747]: I did that in 06e94745ca9d3321fef52a5b454324da84224bf9, and I enhanced the test in  842481f3dc40c3e1208748c54efaee6568b5397d to cover more cases.

**Comment by mkarg** [comment]
@HennyNile Thank you very much for your contribution! 👍 😄

**Comment by HennyNile** [comment]
Happy to help!
